# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Favourite.destroy_all
Booking.destroy_all
Exhibit.destroy_all
Museum.destroy_all
Artist.destroy_all
User.destroy_all

# 4 users
User.create(email: "ilayda@exhibitz.com", first_name: "Ilayda", password: "password")
User.create(email: "raul@exhibitz.com", first_name: "Raul", password: "password")
User.create(email: "zita@exhibitz.com", first_name: "Zita", password: "password")
User.create(email: "joel@exhibitz.com", first_name: "Joel", password: "password")

puts "Creating museums..."
# MUSEUMS
tate_modern = Museum.create(name: 'TATE Modern', address: 'Bankside, London SE1 9TG', website: 'https://www.tate.org.uk/', info: "Tate Modern is a modern art gallery located in London. It is Britain's national gallery of international modern art. It is based in the former Bankside Power Station, in the Bankside area of the London Borough of Southwark.
Tate holds the national collection of British art from 1900 to the present day and international modern and contemporary art. Tate Modern is one of the largest museums of modern and contemporary art in the world. As with the UK's other national galleries and museums, there is no admission charge for access to the collection displays, which take up the majority of the gallery space, while tickets must be purchased for the major temporary exhibitions. The gallery is a highly visited museum, with 5,868,562 visitors in 2018, making it the sixth-most visited art museum in the world, and the most visited in Britain.
The collections in Tate Modern consist of works of international modern and contemporary art dating from 1900 until today.
Levels 2, 3 and 4 contain gallery space. Each of those floors is split into a large east and west wing with at least 11 rooms in each. Space between these wings is also used for smaller galleries on levels 2 and 4. The Boiler House shows art from 1900 to the present day.
The Switch House has eleven floors, numbered 0 to 10. Levels 0, 2, 3 and 4 contain gallery space. Level 0 consists of the Tanks, spaces converted from the power station's original fuel oil tanks, while all other levels are housed in the tower extension building constructed above them. The Switch House shows art from 1960 to the present day.
The Turbine Hall is a single large space running the whole length of the building between the Boiler House and the Switch House. At six stories tall it represents the full height of the original power station building. It is cut by bridges between the Boiler House and the Switch House on levels 1 and 4 but the space is otherwise undivided. The western end consists of a gentle ramp down from the entrance and provides access to both sides on level 0. The eastern end provides a very large space that can be used to show exceptionally large artworks due its unusual height.", opening_hours: '9AM - 5PM', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590592423/clifford-PQTs8KD6YUM-unsplash_wwaeho.jpg' )
national_gallery = Museum.create(name: 'National Gallery', address: 'Trafalgar Square, Charing Cross, London WC2N 5DN', website: 'https://www.nationalgallery.org.uk/', info: 'The National Gallery was founded in 1824, it houses a collection of over 2,300 paintings dating from the mid-13th century to 1900.
Unlike comparable museums in continental Europe, the National Gallery was not formed by nationalising an existing royal or princely art collection. It came into being when the British government bought 38 paintings from the heirs of John Julius Angerstein in 1824. After that initial purchase the Gallery was shaped mainly by its early directors, especially Sir Charles Lock Eastlake, and by private donations, which now account for two-thirds of the collection. The collection is smaller than many European national galleries, but encyclopaedic in scope; most major developments in Western painting from Giotto to Cézanne are represented with important works. It used to be claimed that this was one of the few national galleries that had all its works on permanent exhibition, but this is no longer the case.
The present building, the third to house the National Gallery, was designed by William Wilkins from 1832 to 1838. Only the facade onto Trafalgar Square remains essentially unchanged from this time, as the building has been expanded piecemeal throughout its history. Wilkinss building was often criticised for the perceived weaknesses of its design and for its lack of space; the latter problem led to the establishment of the Tate Gallery for British art in 1897.
The Sainsbury Wing, a 1991 extension to the west by Robert Venturi and Denise Scott Brown, is a significant example of Postmodernist architecture in Britain.
In the 21st century there have been three large fundraising campaigns at the Gallery: in 2004, to buy Raphaels Madonna of the Pinks, in 2008, for Titians Diana and Actaeon, and in 2012, Titians Diana and Callisto. Both Titians were bought in tandem with the National Gallery of Scotland for £95 m. Both of these major works were sold from the collection of the Duke of Sutherland.', opening_hours: '9AM - 5PM', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590614472/dillon-pena-0N86gEJGwv4-unsplash_qma8c6.jpg')
natural_history = Museum.create(name: 'Natural History Museum', address: 'Cromwell Rd, South Kensington, London SW7 5BD', website: 'http://www.nhm.ac.uk/visit/getting-here.html', info: 'The Natural History Museum in London is a natural history museum that exhibits a vast range of specimens from various segments of natural history. It is one of three major museums on Exhibition Road in South Kensington, the others being the Science Museum and the Victoria and Albert Museum. The Natural History Museums main frontage, however, is on Cromwell Road.
The museum is home to life and earth science specimens comprising some 80 million items within five main collections: botany, entomology, mineralogy, palaeontology and zoology. The museum is a centre of research specialising in taxonomy, identification and conservation. Given the age of the institution, many of the collections have great historical as well as scientific value, such as specimens collected by Charles Darwin. The museum is particularly famous for its exhibition of dinosaur skeletons and ornate architecture. The Natural History Museum Library contains extensive books, journals, manuscripts, and artwork collections linked to the work and research of the scientific departments; access to the library is by appointment only. The museum is recognised as the pre-eminent centre of natural history and research of related fields in the world.
One of the most famous and certainly most prominent of the exhibits—nicknamed Dippy—is a 105-foot (32 m)-long replica of a Diplodocus carnegii skeleton which was on display for many years within the central hall. The cast was given as a gift by the Scottish-American industrialist Andrew Carnegie, after a discussion with King Edward VII, then a keen trustee of the British Museum. Carnegie paid £2,000 for the casting, copying the original held at the Carnegie Museum of Natural History. The pieces were sent to London in 36 crates, and on 12 May 1905, the exhibit was unveiled to great public and media interest. The real fossil had yet to be mounted, as the Carnegie Museum in Pittsburgh was still being constructed to house it. As word of Dippy spread, Mr Carnegie paid to have additional copies made for display in most major European capitals and in Latin and South America, making Dippy the most-viewed dinosaur skeleton in the world. The dinosaur quickly became an iconic representation of the museum, and has featured in many cartoons and other media, including the 1975 Disney comedy One of Our Dinosaurs Is Missing. After 112 years on display at the museum, the dinosaur replica was removed in early 2017 to be replaced by the actual skeleton of a young blue whale, a 128-year-old skeleton nicknamed Hope.', opening_hours: '9AM - 5PM', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590614549/yeo-khee-oEMoxk1ATx0-unsplash_tv5dsa.jpg')
design = Museum.create(name: 'Design Museum', address: '224-238 Kensington High St, Kensington, London W8 6AG', website: 'https://designmuseum.org', info: "The Design Museum was founded in 1989 by Sir Terence Conran. It was originally located by the River Thames near Tower Bridge, and later relocated to Kensington.
The Design Museum opened in its Kensington location on 24 November 2016.[3] The move gave the museum three times more space than in its previous location at Shad Thames.
The top-floor space under the museum roof houses a permanent display, Designer Maker User, with key objects from the museum’s collection. A restaurant, members’ lounge, residency studio and an events and gallery space are also located on the top floor.
On the first floor, a design and architecture reference library is a resource for students, educators, researchers and designers. It will also include archive material relating to the history of the museum. The Swarovski Foundation Centre for Learning is a suite of learning facilities including a Design Studio, Creative Workshop, two seminar rooms and a Common Room. The Design Museum offices and main reception, a meeting room and a film studio are also located on the first floor.
On the ground floor, the largest gallery in the new Design Museum showcases a programme of temporary exhibitions. Accessible from both Kensington High Street and Holland Park, the atrium welcomes visitors and acts as an events space. A main staircase from the atrium gives access to all floors and offers views to the first and second floors and the hyperbolic paraboloid roof.
A double-height space spanning the two lower levels, Gallery Two hosts a programme of temporary exhibitions dedicated to architecture, fashion, furniture, product and graphic design. The Bakala Auditorium seats 202 people and provide a purpose-designed space for a programme of talks, seminars, debates and public and private events throughout the year. The basement accommodates a collections store, exhibition preparation spaces and a locker area for visitors.
In 2018, the museum won the European Museum of the Year Award.", opening_hours: '10AM - 6PM', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590494612/design_museum_hjet6p.jpg')
science = Museum.create(name: 'Science Museum', address: 'Exhibition Rd, South Kensington, London SW7 2DD', website: 'https://www.sciencemuseum.org.uk/home', info: "The Science museum was founded in 1857 under Bennet Woodcroft from the collection of the Royal Society of Arts and surplus items from the Great Exhibition as part of the South Kensington Museum, together with what is now the Victoria and Albert Museum. It included a collection of machinery which became the Museum of Patents in 1858, and the Patent Office Museum in 1863. This collection contained many of the most famous exhibits of what is now the Science Museum.
In 1883, the contents of the Patent Office Museum were transferred to the South Kensington Museum. In 1885, the Science Collections were renamed the Science Museum and in 1893 a separate director was appointed. The Art Collections were renamed the Art Museum, which eventually became the Victoria and Albert Museum.
When Queen Victoria laid the foundation stone for the new building for the Art Museum, she stipulated that the museum be renamed after herself and her late husband. This was initially applied to the whole museum, but when that new building finally opened ten years later, the title was confined to the Art Collections and the Science Collections had to be divorced from it. On 26 June 1909 the Science Museum, as an independent entity, came into existence.
The Science Museum's present quarters, designed by Sir Richard Allison, were opened to the public in stages over the period 1919–28. This building was known as the East Block, construction of which began in 1913 and temporarily halted by World War I. As the name suggests it was intended to be the first building of a much larger project, which was never realized. However, the Museum buildings were expanded over the following years; a pioneering Children's Gallery with interactive exhibits opened in 1931, the Centre Block was completed in 1961-3, the infill of the East Block and the construction of the Lower & Upper Wellcome Galleries in 1980, and the construction of the Wellcome Wing in 2000 result in the Museum now extending to Queen's Gate.
The Science Museum now holds a collection of over 300,000 items, including such famous items as Stephensons Rocket, Puffing Billy (the oldest surviving steam locomotive), the first jet engine, the Apollo 10 command module, a reconstruction of Francis Crick and James Watsons model of DNA, some of the earliest remaining steam engines (Including an example of a Newcomen steam engine, the world’s first steam engine), a working example of Charles Babbages Difference engine, the first prototype of the 10,000-year Clock of the Long Now, and documentation of the first typewriter. It also contains hundreds of interactive exhibits. A recent addition is the IMAX 3D Cinema showing science and nature documentaries, most of them in 3-D, and the Wellcome Wing which focuses on digital technology. Entrance has been free since 1 December 2001.", opening_hours: '9AM - 6PM', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590675128/design-unsplash_bkyo3y.jpg')
london_transport = Museum.create(name: 'London Transport Museum', address: 'Covent Garden, London WC2E 7BB', website: 'https://www.ltmuseum.co.uk', info: 'The London Transport Museum or LT Museum, based in Covent Garden, London, seeks to conserve and explain the transport heritage of Britains capital city. The majority of the museums exhibits originated in the collection of London Transport, but, since the creation of Transport for London (TfL) in 2000, the remit of the museum has expanded to cover all aspects of transportation in the city.
The museums main facility is located in a Victorian iron and glass building that had formed part of the Covent Garden vegetable, fruit and flower market. It was designed as a dedicated flower market by William Rogers in 1871. The market moved out in 1971, and the building was reopened as the London Transport Museum on 28 March 1980. The collection had been located at Syon Park since 1973 and before that had formed part of the British Transport Museum at Clapham.
On 4 September 2005 the museum closed for a major £22 million refurbishment designed by Bryan Avery of Avery Associates Architects to enable the expansion of the display collection to encompass the larger remit of TfL which administers all forms of public transport. Enhanced educational facilities were also required. The museum reopened on 22 November 2007.
The first parts of the collection were brought together at the beginning of the 20th century by the London General Omnibus Company (LGOC) when it began to preserve buses being retired from service. After the LGOC was taken over by the London Electric Railway (LER), the collection was expanded to include rail vehicles. It continued to expand after the LER became part of the London Passenger Transport Board in the 1930s and as the organisation passed through various successor bodies up to TfL, Londons current transport authority.
The collection has had a number of homes. It was housed as part of the Museum of British Transport at a disused tram depot in Clapham High Street (now a supermarket) from 1963 to 1972, and then at Syon Park in Brentford from 1973 to 1977, before being moved to Covent Garden in 1980. Most of the other exhibits moved to York on formation of the National Railway Museum in 1975.
The Covent Garden building has on display many examples of buses, trams, trolleybuses and rail vehicles from 19th and 20th centuries as well as artefacts and exhibits related to the operation and marketing of passenger services and the impact that the developing transport network has had on the city and its population. The first underground electric train, from 1890, can be seen here.', opening_hours: '10AM - 6PM', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590675117/transport-unsplash_ocm3u6.jpg')

imperial_war = Museum.create(name: 'Imperial War Museum', address: 'Lambeth Road. London, SE1 6HZ', website: 'https://www.iwm.org.uk/visits/iwm-london', info: 'Imperial War Museums (IWM) is a British national museum organisation with branches at five locations in England, three of which are in London. Founded as the Imperial War Museum in 1917, the museum was intended to record the civil and military war effort and sacrifice of Britain and its Empire during the First World War. The museums remit has since expanded to include all conflicts in which British or Commonwealth forces have been involved since 1914. As of 2012, the museum aims to provide for, and to encourage, the study and understanding of the history of modern war and wartime experience.
Originally housed in the Crystal Palace at Sydenham Hill, the museum opened to the public in 1920. In 1924, the museum moved to space in the Imperial Institute in South Kensington, and finally in 1936, the museum acquired a permanent home that was previously the Bethlem Royal Hospital in Southwark. The outbreak of the Second World War saw the museum expand both its collections and its terms of reference, but in the post-war period, the museum entered a period of decline. The 1960s saw the museum redevelop its Southwark building, now referred to as Imperial War Museum London, which serves as the organisations corporate headquarters. During the 1970s, the museum began to expand onto other sites. The first, in 1976, was a historic airfield in Cambridgeshire now referred to as IWM Duxford. In 1978, the Royal Navy cruiser HMS Belfast became a branch of the museum, having previously been preserved for the nation by a private trust. In 1984, the Cabinet War Rooms, an underground wartime command centre, was opened to the public. From the 1980s onwards, the museums Bethlem building underwent a series of multimillion-pound redevelopments, completed in 2000. Finally, 2002 saw the opening of IWM North in Trafford, Greater Manchester, the fifth branch of the museum and the first in the north of England. In 2011, the museum rebranded itself as IWM, standing for "Imperial War Museums".
The museums collections include archives of personal and official documents, photographs, film and video material, and oral history recordings, an extensive library, a large art collection, and examples of military vehicles and aircraft, equipment, and other artefacts.', opening_hours: '9AM - 5PM', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590499787/IWM-unsplash_kexgyc.jpg')
tate_britain = Museum.create(name: 'TATE Britain', address: 'Millbank, London, SW1P 4RG', website: 'https://www.tate.org.uk/visit/tate-britain', info: 'Tate Britain is part of the Tate network of galleries in England,  having opened in 1897. It houses a substantial collection of the art of the United Kingdom since Tudor times, and in particular has large holdings of the works of J. M. W. Turner, who bequeathed all his own collection to the nation. It is one of the largest museums in the country.
The gallery is situated on Millbank, on the site of the former Millbank Prison. Construction, undertaken by Higgs and Hill, commenced in 1893, and the gallery opened on 21 July 1897 as the National Gallery of British Art. However, from the start it was commonly known as the Tate Gallery, after its founder Sir Henry Tate, and in 1932 it officially adopted that name. Before 2000, the gallery housed and displayed both British and modern collections, but the launch of Tate Modern saw Tates modern collections move there, while the old Millbank gallery became dedicated to the display of historical and contemporary British art. As a consequence, it was renamed Tate Britain in March 2000.
The front part of the building was designed by Sidney R. J. Smith with a classical portico and dome behind, and the central sculpture gallery was designed by John Russell Pope. Tate Britain includes the Clore Gallery of 1987, designed by James Stirling, which houses work by J. M. W. Turner. The Clore Gallery has been regarded as an important example of Postmodern architecture, especially in the use of contextual irony: each section of the external facade quotes liberally from the building next to it in regard to materials and detailing.
Crises during its existence include flood damage to work from the River Thames, and bomb damage during World War II. However, most of the collection was in safe storage elsewhere during the war, and a large Stanley Spencer painting, deemed too big to move, had a protective brick wall built in front of it.
In 1970, the building was given Grade II listed status.
In 2012, Tate Britain announced that it had raised the £45 million required to complete a major renovation, largely thanks to a £4.9 million grant from the Heritage Lottery Fund and £1 million given by Tate Members. The museum stayed open throughout the three phases of renovation. Completed in 2013, the newly designed sections were conceived by the architects Caruso St John and included a total of nine new galleries, with reinforced flooring to accommodate heavy sculptures. A second part was unveiled later that year, the centrepiece being the reopening of the buildings Thames-facing entrance as well as a new spiral staircase beneath its rotunda. The circular balcony of the rotundas domed atrium, closed to visitors since the 1920s, was reopened. The gallery also now has a dedicated schools entrance and reception beneath its entrance steps on Millbank and a new archive gallery for the presentation of temporary displays.', opening_hours: '9AM - 5PM', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590499789/TATE_mpIz0jTjGvE-unsplash_nsupms.jpg')
national_portrait = Museum.create(name: 'National Portrait Gallery', address: 'St Martins Place, London, WC2H 0HE', website: 'https://www.npg.org.uk/', info: 'The National Portrait Gallery (NPG) is an art gallery in London housing a collection of portraits of historically important and famous British people. It was the first portrait gallery in the world when it opened in 1856. The gallery moved in 1896 to its current site at St Martins Place, off Trafalgar Square, and adjoining the National Gallery.
The gallery houses portraits of historically important and famous British people, selected on the basis of the significance of the sitter, not that of the artist. The collection includes photographs and caricatures as well as paintings, drawings and sculpture. One of its best-known images is the Chandos portrait, the most famous portrait of William Shakespeare although there is some uncertainty about whether the painting actually is of the playwright.
Not all of the portraits are exceptional artistically, although there are self-portraits by William Hogarth, Sir Joshua Reynolds and other British artists of note. Some, such as the group portrait of the participants in the Somerset House Conference of 1604, are important historical documents in their own right. Often, the curiosity value is greater than the artistic worth of a work, as in the case of the anamorphic portrait of Edward VI by William Scrots, Patrick Branwell Brontës painting of his sisters Charlotte, Emily and Anne, or a sculpture of Queen Victoria and Prince Albert in medieval costume. Portraits of living figures were allowed from 1969. In addition to its permanent galleries of historical portraits, the National Portrait Gallery exhibits a rapidly changing selection of contemporary work, stages exhibitions of portrait art by individual artists and hosts the annual BP Portrait Prize competition.
The three people largely responsible for the founding of the National Portrait Gallery are commemorated with busts over the main entrance. At centre is Philip Henry Stanhope, 4th Earl Stanhope, with his supporters on either side, Thomas Babington Macaulay, 1st Baron Macaulay (to Stanhopes left) and Thomas Carlyle (to Stanhopes right). It was Stanhope who, in 1846 as a Member of Parliament (MP), first proposed the idea of a National Portrait Gallery. It was not until his third attempt, in 1856, this time from the House of Lords, that the proposal was accepted. With Queen Victorias approval, the House of Commons set aside a sum of £2000 to establish the gallery. As well as Stanhope and Macaulay, the founder Trustees included Benjamin Disraeli and Lord Ellesmere. It was the latter who donated the Chandos portrait to the nation as the gallerys first portrait. Carlyle became a trustee after the death of Ellesmere in 1857.', opening_hours: '9AM - 5PM', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590499784/national_portrait_museaum_barnard-X-OZj_9j7lA-unsplash_icnn78.jpg')
v_and_a = Museum.create(name: "V&A Museum", address: "Cromwell Road, London, SW7 2RL", website: "https://www.vam.ac.uk/", info: "The Victoria and Albert Museum is the world's largest museum of applied and decorative arts and design, as well as sculpture, housing a permanent collection of over 2.27 million objects. It was founded in 1852 and named after Queen Victoria and Prince Albert.
The V&A covers 12.5 acres (5.1 ha) and 145 galleries. Its collection spans 5,000 years of art, from ancient times to the present day, from the cultures of Europe, North America, Asia and North Africa. However, the art of antiquity in most areas is not collected. The holdings of ceramics, glass, textiles, costumes, silver, ironwork, jewellery, furniture, medieval objects, sculpture, prints and printmaking, drawings and photographs are among the largest and most comprehensive in the world.
The museum owns the world's largest collection of post-classical sculpture, with the holdings of Italian Renaissance items being the largest outside Italy. The departments of Asia include art from South Asia, China, Japan, Korea and the Islamic world. The East Asian collections are among the best in Europe, with particular strengths in ceramics and metalwork, while the Islamic collection is amongst the largest in the Western world. Overall, it is one of the largest museums in the world.
Since 2001, the museum has embarked on a major £150m renovation programme. New 17th- and 18th-century European galleries were opened on 9 December 2015. These restored the original Aston Webb interiors and host the European collections 1600–1815. The V&A Museum of Childhood in East London is a branch of the museum, and a new branch in London is being planned.
The Victoria and Albert Museum has its origins in the Great Exhibition of 1851, with which Henry Cole, the museum's first director, was involved in planning. Initially it was known as the Museum of Manufactures, first opening in May 1852 at Marlborough House, but by September had been transferred to Somerset House. At this stage the collections covered both applied art and science. Several of the exhibits from the Exhibition were purchased to form the nucleus of the collection.
By February 1854 discussions were underway to transfer the museum to the current site and it was renamed South Kensington Museum. In 1855 the German architect Gottfried Semper, at the request of Cole, produced a design for the museum, but it was rejected by the Board of Trade as too expensive. The site was occupied by Brompton Park House; this was extended in 1857, including the first refreshment rooms opened—the museum being the first in the world to provide such a facility.
The official opening by Queen Victoria was on 20 June 1857. In the following year, late night openings were introduced, made possible by the use of gas lighting. This was to enable in the words of Cole to ascertain practically what hours are most convenient to the working classes—this was linked to the use of the collections of both applied art and science as educational resources to help boost productive industry. In these early years the practical use of the collection was very much emphasised as opposed to that of High Art at the National Gallery and scholarship at the British Museum. George Wallis (1811–1891), the first Keeper of Fine Art Collection, passionately promoted the idea of wide art education through the museum collections. This led to the transfer to the museum of the School of Design that had been founded in 1837 at Somerset House; after the transfer it was referred to as the Art School or Art Training School, later to become the Royal College of Art which finally achieved full independence in 1949. From the 1860s to the 1880s the scientific collections had been moved from the main museum site to various improvised galleries to the west of Exhibition Road. In 1893 the Science Museum had effectively come into existence when a separate director was appointed." , opening_hours: '9AM - 5PM', image: "https://res.cloudinary.com/dofvu2msx/image/upload/v1590493184/brett-jordan-Fj9CrYkxlqM-unsplash_hwfhk9.jpg")
british = Museum.create(name: "British Museum", address: "Great Russell Street, London WC1B 3DG", website: "https://www.britishmuseum.org/", info: "The British Museum was established in 1753, largely based on the collections of the Irish physician and scientist Sir Hans Sloane. It first opened to the public in 1759, in Montagu House, on the site of the current building. Its expansion over the following 250 years was largely a result of expanding British colonisation and has resulted in the creation of several branch institutions, the first being the Natural History Museum in 1881. In 1973, the British Library Act 1972 detached the library department from the British Museum, but it continued to host the now separated British Library in the same Reading Room and building as the museum until 1997. The museum is a non-departmental public body sponsored by the Department for Digital, Culture, Media and Sport, and as with all national museums in the UK it charges no admission fee, except for loan exhibitions.
Its ownership of some of its most famous objects originating in other countries is disputed and remains the subject of international controversy, most notably in the case of the Elgin Marbles of Greece and the Rosetta Stone of Egypt.
Today, the British Museum has grown to become one of the largest museums in the world, covering an area of over 92,000 m2 (990,000 sq. ft). In addition to 21,600 m2 (232,000 sq. ft) of on-site storage space, and 9,400 m2 (101,000 sq. ft) of external storage space. Altogether the British Museum showcases on public display less than 1% of its entire collection, approximately 50,000 items. There are nearly one hundred galleries open to the public, representing 2 miles (3.2 km) of exhibition space, although the less popular ones have restricted opening times. However, the lack of a large temporary exhibition space has led to the £135 million World Conservation and Exhibition Centre to provide one and to concentrate all the museum's conservation facilities into one Conservation Centre. This project was announced in July 2007, with the architects Rogers Stirk Harbour and Partners. It was granted planning permission in December 2009 and was completed in time for the Viking exhibition in March 2014.
Blythe House in West Kensington is used by the museum for off-site storage of small and medium-sized artefacts, and Franks House in East London is used for storage and work on the Early Prehistory – Palaeolithic and Mesolithic – and some other collections.", opening_hours: '9AM - 5PM', image: "https://res.cloudinary.com/dofvu2msx/image/upload/v1590493502/yaopey-yong-mA-EQLCggng-unsplash_jaagyq.jpg")
national_maritime = Museum.create(name: "National Maritime Museum", address: "Romney Road, Greenwich, London SE10 9NF", website: "https://www.rmg.co.uk/national-maritime-museum", info: "The National Maritime Museum (NMM) was created by the National Maritime Act of 1934 Chapter 43, under a Board of Trustees, appointed by HM Treasury. It is based on the generous donations of Sir James Caird (1864–1954). King George VI formally opened the museum on 27 April 1937 when his daughter Princess Elizabeth accompanied him for the journey along the Thames from London. The first Director was Sir Geoffrey Callender.
Since the earliest times Greenwich has had associations with the sea and navigation. It was a landing place for the Romans, Henry VIII lived here, the Navy has roots on the waterfront, and Charles II founded the Royal Observatory in 1675 for finding the longitude of places. The home of Greenwich Mean Time and the Prime Meridian since 1884, Greenwich has long been a centre for astronomical study, while navigators across the world have set their clocks according to its time of day. The Museum has the most important holdings in the world on the history of Britain at sea comprising more than two million items, including maritime art (both British and 17th-century Dutch), cartography, manuscripts including official public records, ship models and plans, scientific and navigational instruments, instruments for time-keeping and astronomy (based at the Observatory). Its holdings including paintings relating to Vice-Admiral Horatio Nelson and Captain James Cook.
The museum was officially established in 1934 within the 200 acres (0.81 km2) of Greenwich Royal Park in the buildings formerly occupied by the Royal Hospital School, before it moved to Holbrook in Suffolk.
The gardens immediately to the north of the museum were reinstated in the late 1870s following construction of the cut-and-cover tunnel between Greenwich and Maze Hill stations. The tunnel comprised part of the final section of the London and Greenwich Railway and opened in 1878.
A full redevelopment of the main galleries, centring on what is now the Neptune Court, which was designed by Rick Mather Architects and funded by the Heritage Lottery Fund, was completed in 1999.
For a year between 2016 and 2017 the National Maritime Museum reported 2.41 million visitors." , opening_hours: '10AM - 5PM', image: "https://res.cloudinary.com/dofvu2msx/image/upload/v1590494007/robert-bye-Zwt8uyfNklo-unsplash_rrtzj7.jpg")

puts "Creating artist"

# ARTISTS
artist_1 = Artist.create(name: 'Dora Maurer', info: 'Dóra Maurer (born 1937 in Budapest) is a Hungarian visual artist whose work has spanned a 50-year career. She works in almost every medium, from film and photography to painting, performance and sculpture. Principally achieving recognition in the 1970s with avant-garde work, Maurer has developed her art career from works with contemporary and modern influences that have been shown worldwide. Her art is based on mathematical and complex system processes. Most of Maurers work follows the theme of showing options to the viewer and what the viewer can do with those options. Many of her works break down simple actions so the viewer can really view the piece as movement, not a photograph of movement. Dóra Maurer has in addition been a professor at the Faculty of Fine Arts in Budapest and a curator.
In Dóra Maurers work, geometric, mathematical, and conceptual systems all appear. These are the processes in which her mind thinks when creating her art. Dóra Maurer explores different cycles in showing things such as simple actions to make the viewer see her art as movement. She simply gives the viewer examples of things she can do with different objects, to make them think about what they would do. All of Maurers work displays geometric compositions and designs. She is very methodical with the composition she uses, the images, lines, width of lines, colors, angles, and more. Some of her best known works come from her quasi-photos, her series Reversible and Changeable Phases of Movement, and her most recent series, Overlappings.
In 2019 to 2020, she was the subject of a major retrospective exhibition at the Tate Modern. White Cube Gallery began to represent Maurer in 2019.', category: 'Modern, Multimedia', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590597517/niklas_hamann-7HAce_ezHKY-unsplash_umrz2s.jpg')
artist_2 = Artist.create(name: 'Michael Abberley', info: 'British artist 1947-2008', category: 'Pottery designer', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590499785/halanna-halila-baDpsfyw6q4-unsplash_tdqbg3.jpg')
artist_3 = Artist.create(name: 'James Abbe', info: 'James Edward Abbe (July 17, 1883 – November 11, 1973) was an American photographer.
He was born in 1883 in Alfred, Maine. His career as international photographer was first boosted by the Washington Post, which commissioned him to travel and take photographs of a 16-day voyage with the American battleship fleet to England and France in 1910. Many years later he traveled throughout Europe as a young photojournalist in the late 1920s and early 1930s recording the unstable power struggles of the early 20th century. However, he first made a name for himself photographing theatre stars of the New York stage and subsequently movie stars in New York, Hollywood, Paris, and London throughout the 1920s and 1930s. His unusual technique of working outside the studio set him apart from other photographers of the period. To make money, Abbe sold his photographs to magazines such as Vogue and Vanity Fair, which brought his subjects greater fame.
Abbes most celebrated portraits include his rare double portraits of silent film stars Rudolph Valentino and his wife Natasha Rambova, Lillian and Dorothy Gish, as well as dancers including the Dolly Sisters and Anna Pavlova, all taken in the 1920s. Reflecting the changing fashions in magazines content, Abbe became one of the first photojournalist to submit his work in photo-essays to major publications, including The London Magazine, Vu and the Berliner Illustrirte Zeitung. He also took photographs during the Spanish Civil War and the Nazis rise in Germany.', category: 'Photographer', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590500434/james-coleman-IboveVcO7r8-unsplash_vypmd3.jpg')
artist_4 = Artist.create(name: 'George Gammon Adams', info: 'George Gammon Adams (1821–1898; sometimes spelled George Gamon Adams or George Cannon Adams) was an English portrait sculptor and medallist, noted for his statue of General Charles Napier in Trafalgar Square.
Adams was born on 21 April 1821, in Staines, Middlesex, the son of an upholsterer. He entered the Royal Academy Schools in 1840 on the recommendation of the medallist William Wyon. He won a silver medal at the Academy in the same year. He was also taught to model and cut medals and coin dies by Benedetto Pistrucci.
After a year in Rome studying under John Gibson in 1846, he returned to London and worked for Wyon at the Royal Mint on Tower Hill.
He exhibited several works at the Great Exhibition of 1851, and was one of the three artists whose designs were used on the medals awarded to exhibitors. In the following year he was given the honour of making the death mask of the Duke of Wellington. Over the next two decades he produced busts of notable people and other public monuments.
Adams exhibited at the RA 1841–85. He died at his home, Acton Green Lodge, Chiswick, on 14 March 1898.', category: 'Sculptor', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590500566/daniel-robert-I3z6YXsIfIM-unsplash_ywbqv7.jpg')
artist_5 = Artist.create(name: 'Lorenzo Agius', info: '(1962-) Agius studied Art and Art History at the University of East Anglia, moved to London in 1983 and started to assist in photography.', category: 'Photographer', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590500643/angello-pro-IegYaCY101s-unsplash_d3rd2m.jpg' )
artist_6 = Artist.create(name: "Jotaro Saito", info: "Having begun his career designing both western clothing and kimono, at the age of 27, Jotaro Saito made the decision to concentrate solely on the latter. The experience gained through designing western styles greatly influenced the direction of his kimono.", category: "Fashion", image: "https://res.cloudinary.com/dofvu2msx/image/upload/v1590499623/JOTAROSAITO_portrait_tgyypj.jpg")
artist_7 = Artist.create(name: "Imma Ramos", info: "Imma Ramos is curator of the South Asia collections at the British Museum in London. Her research interests revolve around the relationship between religion, politics and gender in South Asian visual culture.", category: "Asian, British, History", image: "https://res.cloudinary.com/dofvu2msx/image/upload/v1590500092/kim-jones-EcldzGBAB0A-unsplash_aoq7cn.jpg")
artist_8 = Artist.create(name: "László Francsics", info: "László Francsics, president of the Association of Hungarian Astrophotographers, has won three awards with his photographs in this years’ Astronomy Photographer of the Year 2019.", category: "Photography", image: "https://res.cloudinary.com/dofvu2msx/image/upload/v1590500500/alasdair-elmes-jQR05LubOgw-unsplash_pkfoeb.jpg")
artist_9 = Artist.create(name: 'Léon Spilliaert', info: 'Léon Spilliaert (also Leon Spilliaert; 28 July 1881 – 23 November 1946) was a Belgian symbolist painter and graphic artist.
Spilliaert was born in Ostend, the oldest of seven children of Léonard-Hubert Spilliaert, a perfumer, and his wife Léonie (née Jonckheere). From childhood, he displayed an interest in art and drawing. A prolific doodler and autodidact, he was predominantly a self-taught artist. Sickly and reclusive, he spent most of his youth sketching scenes of ordinary life and the Belgian countryside.
When he was 21, Spilliaert went to work in Brussels for Edmond Deman, a publisher of the works of symbolist writers, which Spilliaert was to illustrate. He especially admired the work of Edgar Allan Poe.
Watercolor, gouache, pastel, and charcoal—often in combination—were the means by which he produced many of his best works, among which are a number of monochrome self-portraits executed in the early years of the twentieth century. Spilliaerts expressive use of black finds parallels in the work of Odilon Redon, who was a significant influence. Frequently depicting a lone figure in a dreamlike space, Spilliaerts paintings convey a sense of melancholy and silence.
His later work shows a concentration on seascapes. He died on 23 November 1946 in Brussels.', category: 'Symbolism, Expressionism', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590496063/L%C3%A9on_Spilliaert_-_Self_Portrait_-_Met_-_1980.208_fzncxx.jpg')
artist_10 = Artist.create(name: 'Geoffrey Clarke', info: 'Geoffrey Clarke (28 November 1924 – 30 October 2014) was a sculptor of ecclesiastical art and maker of stained glass.
Clarke was a pioneer in a golden age of British sculpture and his fearless experimentation with new materials and processes saw him create works that epitomise the vibrancy of the post-war British art scene.
Clarke was a student of Ronald Grimshaw and attended the Royal College of Art in 1948 after serving in the RAF. He received the silver medal at the Milan Triennale for a collaboration with the furniture designer, Robin Day. He was part of a group of artists including Lynn Chadwick, Reg Butler and Kenneth Armitage who in 1952 was exhibited in the British Pavilion at the Venice Biennale. They were described by art critic Herbert Read as the geometry of fear sculptors. He was commissioned to create the cross of nails for Coventry Cathedral and also worked on three of the nave windows between 1957 and 1962. In 1965 he had a retrospective at The Redfern Gallery, London and his work is also held at the Tate Gallery. Clarke was made a Royal Academician in 1975.
He was the subject of the Shell Film Unit film Cast in a New Mould.', category: 'Sculpture, Ecclesiastical art', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590497135/jen-theodore-9Q_C6rXHQjk-unsplash_xueqwl.jpg')
artist_11 = Artist.create(name: 'David Hockney', info: 'David Hockney (born 9 July 1937) is a British painter, draftsman, printmaker, stage designer, and photographer. As an important contributor to the pop art movement of the 1960s, he is considered one of the most influential British artists of the 20th century.
Hockney has experimented with painting, drawing, printmaking, watercolours, photography, and many other media including fax machine, paper pulp, and computer and iPad drawing programs. The subject matter of interest ranges from still lifes to landscapes, portraits of friends, his dogs, and stage designs for the Royal Court Theatre, Glyndebourne, and the Metropolitan Opera in New York City.
Hockney has owned a home and studio in Bridlington and London, and two residences in California, where he has lived on and off since 1964: one in the Hollywood Hills, one in Malibu, and an office and archives on Santa Monica Boulevard in West Hollywood, California.
On 15 November 2018, Hockneys 1972 work Portrait of an Artist (Pool with Two Figures) sold at Christies auction house in New York City for $90 million (£70 million), becoming the most expensive painting by a living artist sold at auction. This broke the previous record, set by the 2013 sale of Jeff Koons Balloon Dog (Orange) for $58.4 million. Hockney held this record until 15 May 2019, Jeff Koons reclaimed the honour when his Rabbit sold for more than $91 million at Christies in New York.', category: 'Pop art, Cubism', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590496937/david-hockney_lzkpdw.jpg')
artist_12 = Artist.create(name: 'Gregory Bazzle', info: 'Bazzle, self taught and critically acclaimed, began his journey at the end of the 20th century, focussing on transport on first, the roads of London, and then around the world. The utilisation of electricity for the transport in and around London, including its trams and autocars encouraged the travel operators to look for other sources of power. Experiments with steam power and electric batteries were unsuccessful, and the internal combustion petrol engine emerged as the most practical solution. Inspired by the repeal of the Locomotive Act passed in 1897, which abolished the speed restrictions of two miles per hour on horseless carriages and further encouraged the development of the motor vehicles.', category: 'Automative design, painting', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591267517/michele-bergami-0HgnL4MJ0SY-unsplash_eaxrkk.jpg')


puts "Creating exhibits..."
# EXHIBITS
exhibit_1 = Exhibit.create(name: 'Dora Maurer', start_date: '05/03/2019', close_date: '05/06/2020', price: 0, booking_website: 'https://www.tate.org.uk/whats-on/tate-modern/exhibition/dora-maurer', museum_id: tate_modern.id, image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590615128/giulia-may-zdVemwI3hbs-unsplash_qh83js.jpg', image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591199161/robert-keane-rlbG0p_nQOU-unsplash_ptyvjd.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591199312/siora-photography-fz_aFtsHOWQ-unsplash_rik5pb.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591199360/photo-boards-KZNTEn2r6tw-unsplash_iwlpfe.jpg')
exhibit_2 = Exhibit.create(name: 'Sneakers Unboxed: Studio to Street', start_date: '20/06/2020', close_date: '30/09/2020', price: 0, booking_website: 'https://designmuseum.org/exhibitions/sneakers-unboxed-studio-to-street', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590495113/sneakers_bcy8sk.jpg', museum_id: design.id, image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591265271/malvestida-magazine-DMl5gG0yWWY-unsplash_vogtnw.jpg', image2: "https://designmuseum.org/image/52a2fa64-1e63-4943-a875-a8521f89e7dd?width=980&height=606", image3: 'https://designmuseum.org/image/93ff5829-2ddf-429f-8188-83ff23ec7fb3?width=980&height=606')
exhibit_3 = Exhibit.create(name: 'Prada. Front and Back', start_date: '01/07/2020', close_date: '20/10/2020', price: 8, booking_website: 'https://designmuseum.org/exhibitions/prada-front-and-back', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590495902/prada_dwzy42.jpg', museum_id: design.id, image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591200037/ali-pazani-DyIqeZLhIz8-unsplash_jphbje.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591200037/clem-onojeghuo-HpEDSZukJqk-unsplash_x2ihh3.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591200038/alexi-romano-CCx6Fz_CmOI-unsplash_vl14rs.jpg')
exhibit_4 = Exhibit.create(name: 'Léon Spilliaert', start_date: '23/02/2020', close_date: '20/09/2020', price: 14, booking_website: 'https://www.royalacademy.org.uk/exhibition/leon-spilliaert', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590496063/L%C3%A9on_Spilliaert_-_Self_Portrait_-_Met_-_1980.208_fzncxx.jpg', museum_id: national_gallery.id, image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591200573/birmingham-museums-trust-5ruS8plfbvM-unsplash_gqfz0l.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591200573/birmingham-museums-trust-OdtLtgajtyc-unsplash_at3ope.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591200574/nina-z-Rc_gCVM9Wyw-unsplash_twfqj8.jpg')
exhibit_5 = Exhibit.create(name: 'Aubrey Beardsley', start_date: '04/03/2020', close_date: '25/05/2020', price: 0, booking_website: 'https://www.tate.org.uk/whats-on/tate-modern/exhibition/dora-maurer', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590499784/markus-spiske-80BnaHKhKuQ-unsplash_mz4inb.jpg', museum_id: tate_britain.id, image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591200841/mcgill-library-rxZLty9pnh4-unsplash_symlgv.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591200841/mcgill-library-6NSVToSYwV0-unsplash_b5ijvi.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591200841/mcgill-library-dIYFTP3vOxY-unsplash_nlzbpd.jpg')
exhibit_6 = Exhibit.create(name: 'Fly in League with the Night', start_date: '28/02/2020', close_date: '31/08/2020', price: 0, booking_website: 'https://www.tate.org.uk/whats-on/tate-britain/exhibition/lynette-yiadom-boakye', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590499786/audray_jop_BEARDSLEY-unsplash_nkct9h.jpg', museum_id: tate_britain.id, image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201139/mike-von-jgpVWSHvm-8-unsplash_anhykg.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201139/mike-von-bZ_mfIy65x4-unsplash_aawm8c.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201141/mike-von-ro9l9wEzZBA-unsplash_zsvetq.jpg')
exhibit_7 = Exhibit.create(name: 'Hope. Struggle. Change: Photographing Britain and the ​World 1945–79', start_date: '30/06/2020', close_date: '27/10/2020', price: 0, booking_website: 'https://www.tate.org.uk/whats-on/tate-britain/exhibition/hope-struggle-change', image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590499786/quino-al-Lnou48GrIWc-unsplash_lr2jkh.jpg', museum_id: london_transport.id, image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201243/museums-victoria-G10WnM_EEDY-unsplash_jjy3d4.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201241/museums-victoria-oyGmigXV030-unsplash_rrwkyj.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201244/museums-victoria-NGgHlySxH0Q-unsplash_cesxle.jpg')
exhibit_8 = Exhibit.create(name: "Kimono: Kyoto to Catwalk", start_date: "29/02/2020", close_date: "21/06/2020", price: 7, booking_website: "https://www.vam.ac.uk/exhibitions/kimono-kyoto-to-catwalk#vam_nav", image: "https://res.cloudinary.com/dofvu2msx/image/upload/v1590494916/colton-jones--1iRJvwEYtI-unsplash_qsgq6z.jpg", museum_id: v_and_a.id, image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201332/svetlana-gumerova-9_aiGIn1pLM-unsplash_odygbe.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201333/chris-barbalis-F3Gh2z3Mr6I-unsplash_oa7svn.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201337/zhang-kaiyv-9b_VI8EYB3Y-unsplash_whofo7.jpg')
exhibit_9 = Exhibit.create(name: "Tantra, enlightenment to revolution", start_date: "01/07/2020", close_date: "01/10/2020", price: 10, booking_website: "https://www.britishmuseum.org/exhibitions/tantra-enlightenment-revolution", image: "https://res.cloudinary.com/dofvu2msx/image/upload/v1590495118/taylor-simpson-vPblLZXXdVA-unsplash_ymqd1b.jpg", museum_id: british.id, image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201463/nandha-kumar-pj-jTRRhLw8MJc-unsplash_i7k2qj.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201462/sankalp-sharma-DuoAArHvKBw-unsplash_z2jfpf.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201467/brian-kyed-jsvmGh-qmjk-unsplash_dcsyti.jpg')
exhibit_10 = Exhibit.create(name: "Astronomy Photographer of the Year Exhibition", start_date: "03/03/2020", close_date: "16/08/2020", price: 15, booking_website: "https://www.rmg.co.uk/whats-on/astronomy-photographer-year/exhibition#", image: "https://res.cloudinary.com/dofvu2msx/image/upload/v1590495162/greg-rakozy-oMpAz-DN-9I-unsplash_pxsphs.jpg", museum_id: national_maritime.id, image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201551/linda-xu-KsomZsgjLSA-unsplash_asxyfv.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201553/phil-botha-IsTxrLwB0Fk-unsplash_s9dmgi.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201555/john-fowler-d2YMQ-hZ3og-unsplash_x9yaud.jpg')
#####
exhibit_11 = Exhibit.create(name: 'Queer and Now 2020', start_date: '25/07/2020', close_date: '05/12/2020', price: 0, booking_website: 'https://www.tate.org.uk/whats-on/tate-britain/festival/queer-and-now-2020', museum_id: tate_modern.id, image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590594546/jason-dent-y9CFVVirBB8-unsplash_dbmpjd.jpg', image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201702/delia-giandeini-poj5MKZvqkE-unsplash_uqlfw1.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201702/bret-kavanaugh-ge8IxvM5Gxk-unsplash_ga069t.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201706/luis-villasmil-SCYaMb85QuU-unsplash_mi8e6c.jpg')
exhibit_12 = Exhibit.create(name: 'Art in Focus', start_date: '25/01/2020', close_date: '28/11/2020', price: 0, booking_website: 'https://www.tate.org.uk/whats-on/tate-britain/talk/art-focus', museum_id: tate_modern.id, image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590598767/toa-heftiba-qYt-ycKB9IM-unsplash_qixecr.jpg', image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201780/eri-panci-ABdRtZKWJfE-unsplash_yyyohl.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201781/klaudia-piaskowska-g55bG1O5Lf0-unsplash_b4sygx.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201780/igor-miske-oLhTLD-RBsc-unsplash_yvtnha.jpg')
exhibit_13 = Exhibit.create(name: 'Gwen John', start_date: '04/10/2020', close_date: '04/11/2020', price: 0, booking_website: 'https://www.tate.org.uk/visit/tate-britain/display/spotlights/gwen-john', museum_id: tate_modern.id, image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590598975/maria-teneva-QtxcAgSZr4w-unsplash_k6bdf6.jpg', image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201913/boston-public-library-j1n2gBLEi_4-unsplash_dy9r0y.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201914/boston-public-library-fcyB3TjwAOo-unsplash_k7da6z.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591201919/boston-public-library-6b2xPLPN6ag-unsplash_b9vvtm.jpg')
exhibit_14 = Exhibit.create(name: 'Members Private View: Lynette Yiadom-Boakye', start_date: '09/09/2020', close_date: '11/12/2020', price: 5, booking_website: 'https://www.tate.org.uk/whats-on/tate-britain/exhibition/lynette-yiadom-boakye/members-private-view-lynette-yiadom-boakye', museum_id: v_and_a.id, image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590599577/karim-manjra-fm9wqDNXyQ0-unsplash_kihjiw.jpg')
exhibit_15 = Exhibit.create(name: 'Discover 20th Century portraits', start_date: '02/03/2020', close_date: '16/11/2020', price: 0, booking_website: 'https://www.npg.org.uk/collections/explore/discover-20th-century-portraits/', museum_id: national_portrait.id, image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590615866/trevor-cole-nCILef4ExzA-unsplash_kanp5d.jpg', image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591202007/zhu-liang-jRt4LXvGHlc-unsplash_hvxuww.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591202008/daniele-salutari-SxdomihWXRU-unsplash_fpzbfg.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591202010/banjo-emerson-mathew-rvtx9lIABS0-unsplash_e3zuwk.jpg')
exhibit_16 = Exhibit.create(name: 'The Truth Behind Keep Calm and Carry On', start_date: '01/02/2020', close_date: '26/11/2020', price: 0, booking_website: 'https://www.iwm.org.uk/history/truth-behind-keep-calm-and-carry-on', museum_id: imperial_war.id, image: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1590616421/museums-victoria-oyGmigXV030-unsplash_zkfsfn.jpg', image1: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591202094/harry-grout-2I7dsqHeEFw-unsplash_ratlvb.jpg', image2: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591202095/gemma-evans-nLj2TGeAgH8-unsplash_jmvtrr.jpg', image3: 'https://res.cloudinary.com/dofvu2msx/image/upload/v1591202095/paul-jespers-HKqLX9NTtKc-unsplash_eqeuij.jpg')

 puts "Adding some colors to the exhibits..."

ExhibitArtist.create(exhibit_id: exhibit_1.id, artist_id: artist_1.id)
ExhibitArtist.create(exhibit_id: exhibit_2.id, artist_id: artist_2.id)
ExhibitArtist.create(exhibit_id: exhibit_3.id, artist_id: artist_4.id)
ExhibitArtist.create(exhibit_id: exhibit_4.id, artist_id: artist_9.id)
ExhibitArtist.create(exhibit_id: exhibit_5.id, artist_id: artist_5.id)
ExhibitArtist.create(exhibit_id: exhibit_6.id, artist_id: artist_10.id)
ExhibitArtist.create(exhibit_id: exhibit_6.id, artist_id: artist_11.id)
ExhibitArtist.create(exhibit_id: exhibit_7.id, artist_id: artist_3.id)
ExhibitArtist.create(exhibit_id: exhibit_8.id, artist_id: artist_6.id)
ExhibitArtist.create(exhibit_id: exhibit_9.id, artist_id: artist_7.id)
ExhibitArtist.create(exhibit_id: exhibit_10.id, artist_id: artist_8.id)
ExhibitArtist.create(exhibit_id: exhibit_11.id, artist_id: artist_1.id)
ExhibitArtist.create(exhibit_id: exhibit_12.id, artist_id: artist_1.id)
ExhibitArtist.create(exhibit_id: exhibit_13.id, artist_id: artist_12.id)
ExhibitArtist.create(exhibit_id: exhibit_14.id, artist_id: artist_3.id)
ExhibitArtist.create(exhibit_id: exhibit_15.id, artist_id: artist_5.id)
ExhibitArtist.create(exhibit_id: exhibit_16.id, artist_id: artist_7.id)

puts "Seeding complete!"

